### ISSUE TITLE
List Resource Dropdowns Not Clicking Closed

### ISSUE THREAD

**Issue by meagan13** [datagrove/marketplace-us#106]
**Describe the bug**
The dropdown option boxes are not closing upon click

**To Reproduce**
1. Log in
2. Open the menu and click List Resource
3. Scroll down to the Subject, Grade, and Resource Type options boxes
4. Click to open one of the option boxes - options box should open
5. Click again to close the option box - box does not close

**Expected behavior**
The option box opened on click should close on a second click

**Comment by r-southworth** [comment]
Can not reproduce.

**Comment by r-southworth** [comment]
Could not reproduce, made some changes to the dropdowns please create new issue if not resolved 44dadcd7e5e53840616480edf571d5e7c00d1011
