### ISSUE TITLE
Edit Post says "Free Resource?" Instead of "Secular"?

### ISSUE THREAD

**Issue by r-southworth** [datagrove/marketplace-us#120]
**Describe the bug**
A clear and concise description of what the bug is. Please include screenshots in the section below if possible.

**To Reproduce**
1. Go to /post/{number}
2. Click on 'Edit'
4. Free Resource? seems to be doubled (just should say secular instead)

**Expected behavior**
Should say secular

**Screenshots**

<img width="487" alt="Screenshot 2024-08-12 at 1 56 54 PM" src="https://github.com/user-attachments/assets/cceb7b05-9146-478e-89eb-8996c8457432">

**Proposed Solution**
Adjust to point at the correct value in the language files

- [ x ] I am willing to submit a pull request for this issue.

**Comment by gerzarko** [comment]
I fix it and submit PR (https://github.com/datagrove/marketplace-us/pull/124)

**Comment by r-southworth** [comment]
Resolved 3b02d82a0962731b7d7b70ae04a4f2da6b801666
