### ISSUE TITLE
Clear All Filters doesn't clear secular filter 

### ISSUE THREAD

**Issue by r-southworth** [datagrove/marketplace-us#121]
**Describe the bug**
Clear All Filters doesn't clear secular filter 

**To Reproduce**
1. Go to /resources
2. Click on Secular filter
3. Click clear All Filters
4. See Filters not clear secular

**Expected behavior**
All filters should clear

**Proposed Solution**
Update Clear All filters to clear secular filter

- [ x ] I am willing to submit a pull request for this issue.

**Comment by gerzarko** [comment]
I just fix it and submit a PR (https://github.com/datagrove/marketplace-us/pull/124)

**Comment by r-southworth** [comment]
Resolved  c149d9dc0963607c4062d565cfb01924e8bfbee5
