### ISSUE TITLE
Favorites list number increases as you add items to the Default list

### ISSUE THREAD

**Issue by meagan13** [datagrove/marketplace-us#169]
**Describe the bug**
If you favorite a second item the number of resources indicated for the Default list is still 0

**To Reproduce**
1. Add a resource to favorites
2. Add a second resource to favorites
3. Number of resources does not change

**Expected behavior**
Number of resources should change as resources are added

**Proposed Solution**
Might need a createEffect for the add favorites modal

- [ ] I am willing to submit a pull request for this issue.

**Comment by r-southworth** [comment]
4f9f08a73e3c00732d271612fa53ecd7f649f517

**Comment by r-southworth** [comment]
https://github.com/datagrove/marketplace-us/pull/187
