### ISSUE TITLE
Search pulls portions of search terms and pulls resources that aren't an exact match

### ISSUE THREAD

**Issue by meagan13** [datagrove/marketplace-us#173]
**Describe the bug**
Ensuring that it's behaving as desired - when I search for `testing` the search returns anything with even just the word `test` - are we ok with partial word matches for now? It could make the search less helpful.

**To Reproduce**
1. Go to LearnGrove.co
2. Search for the word `testing`
3. Any post with even partial clips of the word `testing` (e.g., `test`) appear - although a post titled `sting` did not appear in that search

**Expected behavior**
Only exact match words appear (`testing` and `testing`, not `testing` and `test`)

- [ ] I am willing to submit a pull request for this issue.

**Comment by r-southworth** [comment]
I believe this is expected behavior for a full text search but we can research further
