### ISSUE TITLE
Price filter - Free Resources

### ISSUE THREAD

**Issue by meagan13** [datagrove/marketplace-us#175]
**Describe the bug**
Clicking the `Free Resources` filter checkbox seems to return all resources, even those that aren't free

**To Reproduce**
1. Got to Resource Catalog page
2. Click Price filter
3. Select the `Free Resources` checkbox
4. Resources of all price points appear

**Expected behavior**
Only free resources should appear when the `Free Resources` checkbox is checked

- [ ] I am willing to submit a pull request for this issue.

**Comment by r-southworth** [comment]
4f9f08a73e3c00732d271612fa53ecd7f649f517

**Comment by r-southworth** [comment]
https://github.com/datagrove/marketplace-us/pull/187
