### ISSUE TITLE
Help Center needs to be replaced by Starlight page

### ISSUE THREAD

**Issue by meagan13** [datagrove/marketplace-us#177]
**Describe the bug**
Help Center needs to be replaced by Starlight page

**Additional context**
Doesn't impact site functionality, but the Starlight page looks nicer and is easier to use

- [ ] I am willing to submit a pull request for this issue.

**Comment by r-southworth** [comment]
4f9f08a73e3c00732d271612fa53ecd7f649f517

**Comment by r-southworth** [comment]
https://github.com/datagrove/marketplace-us/pull/187
