### ISSUE TITLE
Create post image isn't indicated as a required field

### ISSUE THREAD

**Issue by meagan13** [datagrove/marketplace-us#182]
**Describe the bug**
When a Creator creates a post the image upload doesn't have an asterisk indicating that it's a required field, but the form won't allow submission without an image

**To Reproduce**
1. Menu - List Resource
2. Enter all information for a post except an image
3. Submit button is grayed out/not clickable

**Expected behavior**
Able to submit without an image

**Proposed Solution**
Either add an asterisk to images (suggested) or remove the requirement for an image to submit the post

- [ ] I am willing to submit a pull request for this issue.

**Comment by r-southworth** [comment]
https://github.com/datagrove/marketplace-us/pull/187
